require("prototypes.items.pile-of-poo")
require("prototypes.resources.pile-of-poo")

require("prototypes.items.emoji-ore")
require("prototypes.resources.emoji-ore")

require("prototypes.items.meat-ore")
require("prototypes.resources.meat-ore")

require("prototypes.items.crab-ore")
require("prototypes.resources.crab-ore")

require("prototypes.items.turtle-ore")
require("prototypes.resources.turtle-ore")

local util = require('util')

function icon(name)
  return "__Emojitorio__/graphics/icons/" .. name .. ".png"
end

data.raw.item["copper-plate"].icon = icon("crab-card")
data.raw.item["iron-plate"].icon = icon("floppy-disk")
data.raw.item["steel-plate"].icon = icon("e-mail-symbol")
data.raw.item["iron-stick"].icon = icon("spoon")
data.raw.item["iron-gear-wheel"].icon = icon("gear")
data.raw.item["electronic-circuit"].icon = icon("heavy-check-mark")
data.raw["item-with-entity-data"]["car"].icon = icon("automobile")
data.raw["item-with-entity-data"]["tank"].icon = icon("tractor")
data.raw["repair-tool"]["repair-pack"].icon = icon("hammer-and-wrench")
data.raw.capsule["grenade"].icon = icon("bomb")
data.raw.item["advanced-circuit"].icon = icon("cross-mark")
data.raw.item["battery"].icon = icon("battery")
data.raw.item["satellite"].icon = icon("hundred-points-symbol")
data.raw.item["explosives"].icon = icon("firecracker")
data.raw.item["computer"].icon = icon("abacus")
data.raw.item["plastic-bar"].icon = icon("roll-of-paper")
data.raw.item["sulfur"].icon = icon("bar-of-soap")
data.raw.gun["pistol"].icon = icon("pistol")
data.raw.gun["submachine-gun"].icon = icon("banjo")
data.raw.gun["rocket-launcher"].icon = icon("bow-and-arrow")
data.raw.armor["light-armor"].icon = icon("socks")
data.raw.fish.fish.icon = icon("fish")
data.raw.fluid.water.icon = icon("droplet")
data.raw.item["rocket-control-unit"].icon = icon("pager")
data.raw.item["processing-unit"].icon = icon("electric-light-bulb")
data.raw.item["low-density-structure"].icon = icon("scroll")
data.raw.tool["automation-science-pack"].icon = icon("dollar")
data.raw.tool["logistic-science-pack"].icon = icon("euro")
data.raw.tool["chemical-science-pack"].icon = icon("pound")
data.raw.tool["production-science-pack"].icon = icon("yen")
data.raw.tool["military-science-pack"].icon = icon("safety-pin")
data.raw.tool["utility-science-pack"].icon = icon("crayon")
data.raw.armor["power-armor"].icon = icon("dress")
data.raw.armor["power-armor-mk2"].icon = icon("kimono")
data.raw.armor["heavy-armor"].icon = icon("briefs")
data.raw.armor["modular-armor"].icon = icon("t-shirt")
data.raw["night-vision-equipment"]["night-vision-equipment"].sprite.filename = icon("goggles")
data.raw["item"]["night-vision-equipment"].icon = icon("goggles")
data.raw["item"]["copper-cable"].icon = icon("crab-cable")
